apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-prod
patches: 
- path: patch.yaml 
  target: 
    kind: Deployment
    name: hello
  options:
    allowNameChange: true
bases: 
- ../../base
commonLabels:
  env: prod