apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: hello-test
  target:
    kind: Deployment
    name: hello
- patch: |-
    - op: replace
      path: /spec/replicas 
      value: 15
  target:
    kind: Deployment
    name: hello
bases:
- ../../base
commonLabels: 
  env: test