apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
    name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      name: hello
  template:
    metadata:
      labels:
        app: hello
        name: hello
    spec:
      containers:
      - name: hello
        image: quay.io/redhattraining/do480-hello-app:v1.0